version: '3.9'

services:
  db:
    image: postgres:16
    container_name: database_vpn
    restart: always

    env_file:
      - .env

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_web:
    build: .
    container_name: api_web
    restart: always

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
        
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
