version: '3.9'

services:
  db:
    image: postgres:16
    container_name: database_vpn
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d detavpn"]
      interval: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_web:
    build: .
    container_name: api_web
    restart: always

    env_file:
      - .env

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: